_target_: src.models.ssfm.SSFM

embed_config:
  hddn_dim: 64
  num_blocks: 1
  norm: RMSNorm
  act_o: SiLU
  act_h: SiLU
  norm_on_output: True
  dropout: 0.3

encoder_config:
  dim: 64
  ctxt_dim: 32
  num_layers: 3
  num_registers: 4
  pack_inputs: True
  layer_config:
    ff_config:
      dropout: 0.3
    attn_config:
      dropout: 0.3

decoder_config:
  dim: 64 # Must be the same as the encoder
  ctxt_dim: 32
  num_layers: 3
  num_registers: 0 # Must be 0!
  pack_inputs: True
  layer_config:
    ff_config:
      dropout: 0.3
    attn_config:
      dropout: 0.3

optimizer:
  _target_: mltools.mltools.optimisers.AdamWS
  _partial_: True
  lr: 1.0e-3
  betas: [0.9, 0.95]
  weight_decay: 0.1

scheduler:
  _target_: mltools.mltools.lightning_utils.linear_warmup_cosine_decay
  _partial_: True
  warmup_steps: 10_000
  total_steps: -1
